name: FatJar bauen

on:
  push:
    branches: [ "master" ]

jobs:
  job-fatjar:
    runs-on: ubuntu-latest
    steps:
    - name: Git-Repo auschecken
      uses: actions/checkout@v4
    - name: JDK einrichten
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven
    - name: Maven-Installation checken
      run: chmod u+x && ./mvnw --version
    - name: FatJar-Datei mit Maven bauen
      run: ./mvnw --batch-mode clean package
    - name: FatJar-Datei veröffentlichen
      uses: actions/upload-artifact@v4
      with:
        name: Tagenbuch_FatJar
        path: target/tagebuch-*-SNAPSHOT.jar
        if-no-files-found: error
        retention-days: 3